#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""init_ai_tooling.py (2.0.0, AGENTS.md model) — cross-OS counterpart to init-ai-tooling.sh.

Scaffolds an AI tooling layout (Claude, Codex, Cursor, Gemini/Antigravity) in the
current repository. Model: AGENTS.md = single source of truth, read natively by
Codex, Cursor and Antigravity; CLAUDE.md and GEMINI.md import it; .ai/ holds
shared artifacts and the manifest.

Pure stdlib (Python 3.6+), no dependencies. Idempotent (without --force does not
touch existing files). Writes LF line endings on every OS. Output matches the
bash version.

Usage:
    python3 init_ai_tooling.py [--name NAME] [--desc "DESC"] [--force] [--dry-run]
        [--no-gitignore] [--also-repo] [--repo-profile core|github|full]
    python3 init_ai_tooling.py --prune-legacy
"""
import argparse
import datetime
import os
from pathlib import Path
import subprocess
import sys

VERSION = "2.0.0"

# >>> BEGIN GENERATED by tools/sync-templates.py (edit templates/, not this block)
GITKEEP_DIRS = [
    ".ai/artifacts",
    ".claude/commands",
    ".claude/agents",
]

GITIGNORE_LINES = [
    ".env",
    ".env.*",
    "!.env.example",
    "*.local",
    ".claude/settings.local.json",
    ".DS_Store",
]

LEGACY_FILES = [
    ".cursorrules",
    "PERPLEXITY.md",
    ".perplexity/README.md",
    ".antigravity/README.md",
    ".ai/shared-context.md",
    ".cursor/README.md",
    ".cursor/rules/.gitkeep",
    ".perplexity/context.md",
    ".perplexity/spaces/README.md",
    ".antigravity/rules/000-workspace.md",
    ".antigravity/rules/.gitkeep",
]

LEGACY_ARTIFACT_DIRS = [
    ".claude/artifacts",
    ".cursor/artifacts",
    ".antigravity/artifacts",
    ".perplexity/artifacts",
]

# (path, template) in write order.
FILES = [
    ("AGENTS.md", """\
# AGENTS.md — __NAME__

> Shared instructions for AI coding agents and humans. Codex, Cursor, Google Antigravity/Gemini,
> and other AGENTS-compatible tools read this file natively; Claude Code imports it from `CLAUDE.md`.
> Keep it short: write down only what an agent cannot infer from the code.

## Project
__DESC__

<!-- TODO: 1–3 sentences — what it is, who uses it, what matters most. -->

## Commands
<!-- TODO: exact commands an agent should run, e.g. install, test, lint, build. -->

## Conventions
<!-- TODO: only non-obvious rules — module boundaries, generated code not to edit, naming. -->

## Never
- Commit or print secrets (`.env`, keys, tokens); only `*.example` files belong in the repo.
- Run destructive operations on production data without explicit confirmation.
- <!-- TODO: project-specific bans (e.g. do not touch `vendor/`). -->

## Done means
Tests and lint pass for the change. <!-- TODO: add project-specific checks. -->

## Artifacts
Plans, research, and other durable session results from every tool go in `.ai/artifacts/`.
Codex reads this file natively and uses the shared artifacts directory.

<!-- Initialized by init-ai-tooling __VERSION__ (__DATE__). -->
"""),
    (".cursor/rules/000-project.mdc", """\
---
description: Base project context for __NAME__ — points to AGENTS.md
alwaysApply: true
---

# __NAME__

Source of truth — `../../AGENTS.md` (read it fully). This file and sibling `*.mdc`
files hold Cursor-specific and detailed topical rules only.
"""),
    (".cursor/rules/010-safety.mdc", """\
---
description: Security, secrets, production work
alwaysApply: true
---

# Security

- Secrets (passwords, keys, tokens, `.env`, local configs) — not in code, commits, or context.
- Do not edit production directly; destructive operations on production data — only
  with explicit confirmation and a dry run on a copy.
- Before a risky change — show a diff and rollback plan, ask for confirmation.
- Full rules — in `../../AGENTS.md`.
"""),
    (".cursorignore", """\
# Secrets and local config
.env
*.local

# Build artifacts and data
dist/
build/
*.egg-info/

# Environments and caches
.venv/
venv/
node_modules/
__pycache__/
*.py[cod]
.pytest_cache/
.mypy_cache/
.ruff_cache/

.DS_Store
"""),
    ("CLAUDE.md", """\
# CLAUDE.md — __NAME__

Project rules live in `AGENTS.md`; the import below loads it into every Claude Code session.

@AGENTS.md

## Claude-specific
- `.claude/commands/` — slash commands; `.claude/agents/` — subagents.
- Team settings — `.claude/settings.json`; personal — `.claude/settings.local.json` (do not commit).
- `settings.json` deny rules are guardrails, not a sandbox — see `.claude/README.md`.
"""),
    (".claude/README.md", """\
# .claude/ — Claude Code configuration

Source of truth — [`../AGENTS.md`](../AGENTS.md).

- `commands/` — slash commands; `agents/` — subagents. Artifacts go in `../.ai/artifacts/`.
- `settings.json` — team settings; `settings.local.json` — personal (do not commit).

## What `settings.json` does NOT protect
The `deny` list is a best-effort guardrail, not a security boundary:
- `Bash(...)` rules match command prefixes: `rm -r -f`, `find . -delete`, or a script
  that deletes files are not caught.
- Without the sandbox, `Read(...)` rules cover Claude's file tools, not `cat .env` run through Bash.

For real isolation use Claude Code's sandbox, a container/devcontainer, or a `PreToolUse` hook.
"""),
    (".claude/settings.json", """\
{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  "//": "Team Claude Code settings for __NAME_JSON__. Personal overrides — settings.local.json (do not commit). Deny rules are guardrails, not a sandbox: see .claude/README.md.",
  "permissions": {
    "allow": ["Read", "Edit"],
    "deny": [
      "Read(.env)",
      "Read(.env.*)",
      "Read(**.pem)",
      "Read(**.key)",
      "Read(**/.ssh/**)",
      "Read(**/.aws/**)",
      "Read(**/.kube/**)",
      "Bash(rm -rf:*)",
      "Bash(rm -fr:*)",
      "Bash(git push --force:*)",
      "Bash(git push -f:*)"
    ]
  }
}
"""),
    ("GEMINI.md", """\
# GEMINI.md — __NAME__

Project rules live in `AGENTS.md`; the import below loads it into Gemini CLI.
Google Antigravity reads `AGENTS.md` natively.

@./AGENTS.md

## Gemini-specific
<!-- TODO: only what differs for Gemini CLI / Antigravity; leave empty if nothing does. -->
"""),
    (".ai/README.md", """\
# .ai/ — AI tooling layout

**Source of truth — [`../AGENTS.md`](../AGENTS.md)** (read natively by Codex, Cursor,
Antigravity/Gemini, and others). Other files only add tool-specific detail.

| Tool | File | Artifacts |
|---|---|---|
| All agents | `AGENTS.md` | `.ai/artifacts/` |
| Codex (CLI / IDE / app) | `AGENTS.md` (native); optional `.codex/config.toml` | `.ai/artifacts/` |
| Cursor | `AGENTS.md` (native); `.cursor/rules/*.mdc`; `.cursorignore` | `.ai/artifacts/` |
| Claude (Code / Cowork) | `CLAUDE.md` (`@AGENTS.md` import); `.claude/` | `.ai/artifacts/` |
| Gemini CLI / Antigravity | `GEMINI.md` (`@AGENTS.md` import); Antigravity reads `AGENTS.md` | `.ai/artifacts/` |

## Rule
Project changes → edit **`AGENTS.md`**. Tool-specific detail → that tool's file.
Codex needs no redirect file; add `.codex/config.toml` only for concrete repository-specific
settings. An artifact is a durable session result (plan, research, diff, task list).
`manifest.json` lists the files this kit generated; `--prune-legacy` reports leftovers
from older kit versions.

<!-- Initialized by init-ai-tooling __VERSION__ (__DATE__). -->
"""),
    (".ai/manifest.json", """\
{
  "generator": "init-ai-tooling __VERSION__",
  "created": "__DATE__",
  "files": [
    "AGENTS.md",
    ".cursor/rules/000-project.mdc",
    ".cursor/rules/010-safety.mdc",
    ".cursorignore",
    "CLAUDE.md",
    ".claude/README.md",
    ".claude/settings.json",
    "GEMINI.md",
    ".ai/README.md",
    ".ai/manifest.json"
  ],
  "dirs": [
    ".ai/artifacts",
    ".claude/commands",
    ".claude/agents"
  ]
}
"""),
]
# <<< END GENERATED


def report_legacy():
    """List leftovers generated by older kit versions. Never deletes anything."""
    found = 0
    say("Legacy paths from earlier kit versions (nothing is deleted):")
    for rel in LEGACY_FILES:
        if os.path.isfile(rel):
            say("  " + rel)
            found += 1
    for rel in LEGACY_ARTIFACT_DIRS:
        if not os.path.isdir(rel):
            continue
        found += 1
        try:
            saved = [entry for entry in os.listdir(rel) if entry != ".gitkeep"]
        except OSError:
            say("  %s/ (unreadable: check it manually)" % rel)
            continue
        if saved:
            say("  %s/ (%d saved item(s): move them to .ai/artifacts/ first)" % (rel, len(saved)))
        else:
            say("  %s/" % rel)
    if found:
        say("Review each path, then remove it, e.g.: git rm -r <path>")
    else:
        say("  none found")
    return 0


def say(msg=""):
    print(msg)


def render(text, name, desc, date, version=VERSION):
    # __NAME_JSON__ — name escaped for JSON substitution: quotes and backslashes
    # would otherwise invalidate .claude/settings.json.
    name_json = name.replace("\\", "\\\\").replace('"', '\\"')
    return (text.replace("__NAME_JSON__", name_json)
                .replace("__NAME__", name)
                .replace("__DESC__", desc)
                .replace("__DATE__", date)
                .replace("__VERSION__", version))


def main(argv=None):
    p = argparse.ArgumentParser(
        prog="init_ai_tooling.py",
        description="AI tooling scaffold (AGENTS.md model).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Creates: AGENTS.md (source of truth, read natively by Codex, Cursor, "
            "Antigravity), .cursor/rules/*.mdc + .cursorignore, CLAUDE.md + .claude/ "
            "(@AGENTS.md import), GEMINI.md (@AGENTS.md import), .ai/ (layout map, "
            "manifest, shared artifacts)."
        ),
    )
    p.add_argument("--name", default="", help="Project name (defaults to the folder name).")
    p.add_argument("--desc", default="", help="One-line description.")
    p.add_argument("--force", action="store_true", help="Overwrite existing files.")
    p.add_argument("--dry-run", action="store_true", help="Print the plan, write nothing.")
    p.add_argument("--no-gitignore", action="store_true", help="Leave .gitignore alone.")
    p.add_argument(
        "--also-repo",
        action="store_true",
        help="Also run sibling init_repo_bootstrap.py (B+).",
    )
    p.add_argument(
        "--repo-profile",
        default="full",
        choices=("core", "github", "full"),
        help="Profile for --also-repo (default: full; standalone companion defaults to core).",
    )
    p.add_argument(
        "--prune-legacy",
        action="store_true",
        help="List leftovers from older kit versions and exit (deletes nothing).",
    )
    p.add_argument(
        "--version",
        action="version",
        version="%(prog)s " + VERSION,
        help="Print version and exit.",
    )
    args = p.parse_args(argv)
    if args.prune_legacy:
        return report_legacy()

    name = args.name or os.path.basename(os.getcwd())
    desc = args.desc or "TODO: short project description"
    date = datetime.date.today().isoformat()
    force, dry = args.force, args.dry_run

    def ensure_dir(d: Path):
        if dry:
            say("mkdir  " + str(d).replace(os.sep, "/"))
        else:
            d.mkdir(parents=True, exist_ok=True)

    def gitkeep(d_str: str):
        p = Path(d_str)
        ensure_dir(p)
        f = p / ".gitkeep"
        if f.exists() and not force:
            return
        if dry:
            say("touch  " + str(f).replace(os.sep, "/"))
            return
        try:
            f.touch()
        except OSError as e:
            say("error  failed to create %s: %s" % (f, e))
            sys.exit(1)

    def write_file(path_str: str, content: str):
        p = Path(path_str)
        if p.exists() and not force:
            say("skip   " + path_str + " (already exists)")
            return
        if dry:
            say("write  " + path_str)
            return
        try:
            p.parent.mkdir(parents=True, exist_ok=True)
            # newline="\n" — LF on every OS (including Windows), matching bash
            with open(p, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(content)
            say("write  " + path_str)
        except OSError as e:
            say("error  failed to write %s: %s" % (path_str, e))
            sys.exit(1)

    # 1) artifact directories + .gitkeep
    for d in GITKEEP_DIRS:
        gitkeep(d)

    # 2) files
    for rel, tpl in FILES:
        write_file(rel, render(tpl, name, desc, date))

    # 3) .gitignore
    if not args.no_gitignore:
        gitignore_path = Path(".gitignore")
        existing_lines = []
        if gitignore_path.exists():
            try:
                with open(gitignore_path, "r", encoding="utf-8") as fh:
                    existing_lines = fh.read().splitlines()
            except OSError as e:
                say("warning failed to read .gitignore: %s" % e)

        for line in GITIGNORE_LINES:
            if line not in existing_lines:
                if dry:
                    say("gitignore += " + line)
                    continue
                try:
                    needs_newline = False
                    if gitignore_path.exists() and gitignore_path.stat().st_size > 0:
                        with open(gitignore_path, "rb") as fh:
                            fh.seek(-1, os.SEEK_END)
                            if fh.read(1) != b"\n":
                                needs_newline = True
                    with open(gitignore_path, "a", encoding="utf-8", newline="\n") as fh:
                        if needs_newline:
                            fh.write("\n")
                            needs_newline = False
                        fh.write(line + "\n")
                    existing_lines.append(line)
                except OSError as e:
                    say("warning failed to update .gitignore: %s" % e)

    say("")
    say('Done (%s): AGENTS.md-model scaffold deployed for "%s".' % (VERSION, name))
    say("Next: fill in the TODOs in AGENTS.md — every tool reads context from there.")

    if args.also_repo:
        companion = Path(__file__).resolve().parent / "init_repo_bootstrap.py"
        if not companion.is_file():
            say("error: --also-repo requires init_repo_bootstrap.py next to this script")
            say("       expected: %s" % companion)
            return 1
        say("")
        say("Also-repo: invoking init_repo_bootstrap.py --profile %s" % args.repo_profile)
        cmd = [
            sys.executable,
            str(companion),
            "--name", name,
            "--desc", desc,
            "--profile", args.repo_profile,
        ]
        if force:
            cmd.append("--force")
        if dry:
            cmd.append("--dry-run")
        rc = subprocess.call(cmd)
        if rc != 0:
            return rc
    else:
        say(
            "Tip: run init_repo_bootstrap.py (or re-run with --also-repo) "
            "for LICENSE/SECURITY/CHANGELOG stubs."
        )

    if dry and not args.also_repo:
        say("(dry-run: nothing was written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
