#!/usr/bin/env bash
# init-ai-tooling.sh (1.3.0, AGENTS.md model) — deploys an AI tooling scaffold
# (Claude, Codex, Cursor, Antigravity/Gemini, Perplexity) in the current repository.
#
# Model: AGENTS.md = single source of truth (read natively by Codex, Cursor,
# Antigravity/Gemini, and others). Everything else — thin redirect/specific files
# at the root (.cursorrules, CLAUDE.md, GEMINI.md, PERPLEXITY.md). `.ai/` — artifacts only.
#
# Idempotent (without --force does not touch existing files). Self-contained (templates inside).
set -euo pipefail

VERSION="1.3.0"
NAME=""; DESC=""; FORCE=0; DRYRUN=0; NO_GITIGNORE=0
ALSO_REPO=0; REPO_PROFILE="full"

usage() {
  cat <<USAGE
init-ai-tooling.sh (${VERSION}) — AI tooling scaffold (AGENTS.md model).

Usage:
  init-ai-tooling.sh [--name NAME] [--desc "DESC"] [--force] [--dry-run] [--no-gitignore]
                     [--also-repo] [--repo-profile core|github|full]

Options:
  --name NAME       Project name (defaults to the folder name).
  --desc TEXT       Short one-line description.
  --force           Overwrite existing files.
  --dry-run         Print the plan, write nothing.
  --no-gitignore    Leave .gitignore alone.
  --also-repo       Also run sibling init-repo-bootstrap.sh (B+).
  --repo-profile P  Profile for --also-repo (default: full).
  --version         Print version and exit.
  -h, --help        Show this help.

Creates:
  AGENTS.md                ★ source of truth (native Codex + all agent rules)
  .cursorrules             redirect → AGENTS.md (legacy Cursor)
  .cursor/rules/*.mdc      detailed rules (000-project, 010-safety) + .cursorignore
  CLAUDE.md                redirect → AGENTS.md (Claude Code / Cowork)
  GEMINI.md                Antigravity/Gemini specifics (wins on conflict)
  PERPLEXITY.md            paste-in brief for Perplexity / research agents
  .ai/                     layout map + shared/Codex artifacts
  .claude/ .cursor/ .antigravity/ .perplexity/  — tool-specific artifacts
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --name) NAME="${2:-}"; shift 2 ;;
    --desc) DESC="${2:-}"; shift 2 ;;
    --force) FORCE=1; shift ;;
    --dry-run) DRYRUN=1; shift ;;
    --no-gitignore) NO_GITIGNORE=1; shift ;;
    --also-repo) ALSO_REPO=1; shift ;;
    --repo-profile)
      REPO_PROFILE="${2:-}"
      case "$REPO_PROFILE" in
        core|github|full) ;;
        *) echo "Unknown --repo-profile: $REPO_PROFILE (expected core|github|full)" >&2; exit 2 ;;
      esac
      shift 2
      ;;
    --version) printf '%s\n' "init-ai-tooling.sh ${VERSION}"; exit 0 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

[ -n "$NAME" ] || NAME="$(basename "$(pwd)")"
[ -n "$DESC" ] || DESC="TODO: short project description"
DATE="$(date +%Y-%m-%d)"

say() { printf '%s\n' "$*"; }
ensure_dir() { [ "$DRYRUN" = "1" ] && { say "mkdir  $1"; return 0; }; mkdir -p "$1"; }
gitkeep() {
  ensure_dir "$1"; local f="$1/.gitkeep"
  [ -e "$f" ] && [ "$FORCE" != "1" ] && return 0
  [ "$DRYRUN" = "1" ] && { say "touch  $f"; return 0; }
  : > "$f"
}
write_file() {
  local path="$1"
  if [ -e "$path" ] && [ "$FORCE" != "1" ]; then say "skip   $path (already exists)"; cat >/dev/null; return 0; fi
  if [ "$DRYRUN" = "1" ]; then say "write  $path"; cat >/dev/null; return 0; fi
  mkdir -p "$(dirname "$path")"; cat > "$path"; say "write  $path"
}
escape_sed() {
  printf '%s' "$1" | sed -e 's/[\\&|]/\\&/g'
}
# Escape for JSON substitution: quotes and backslashes in the project name
# would otherwise invalidate .claude/settings.json.
escape_json() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}
render() {
  local safe_name safe_desc safe_date safe_name_json safe_version
  safe_name="$(escape_sed "$NAME")"
  safe_desc="$(escape_sed "$DESC")"
  safe_date="$(escape_sed "$DATE")"
  safe_version="$(escape_sed "$VERSION")"
  safe_name_json="$(escape_sed "$(escape_json "$NAME")")"
  sed -e "s|__NAME_JSON__|${safe_name_json}|g" -e "s|__NAME__|${safe_name}|g" \
      -e "s|__DESC__|${safe_desc}|g" -e "s|__DATE__|${safe_date}|g" \
      -e "s|__VERSION__|${safe_version}|g"
}

# >>> BEGIN GENERATED by tools/sync-templates.py (edit templates/, not this block)
GITKEEP_DIRS=('.ai/artifacts' '.claude/commands' '.claude/agents' '.claude/artifacts' '.cursor/artifacts' '.antigravity/artifacts' '.perplexity/artifacts')
GITIGNORE_LINES=('.env' '.env.*' '!.env.example' '*.local' '.claude/settings.local.json' '.DS_Store')

# Writes every template in order (render | write_file).
emit_templates() {
render <<'TPL' | write_file "AGENTS.md"
# AGENTS.md — __NAME__

> Shared instructions for AI coding agents and humans. Codex, Cursor, Google Antigravity/Gemini,
> and other AGENTS-compatible tools read this file natively; Claude Code imports it from `CLAUDE.md`.
> Keep it short: write down only what an agent cannot infer from the code.

## Project
__DESC__

<!-- TODO: 1–3 sentences — what it is, who uses it, what matters most. -->

## Commands
<!-- TODO: exact commands an agent should run, e.g. install, test, lint, build. -->

## Conventions
<!-- TODO: only non-obvious rules — module boundaries, generated code not to edit, naming. -->

## Never
- Commit or print secrets (`.env`, keys, tokens); only `*.example` files belong in the repo.
- Run destructive operations on production data without explicit confirmation.
- <!-- TODO: project-specific bans (e.g. do not touch `vendor/`). -->

## Done means
Tests and lint pass for the change. <!-- TODO: add project-specific checks. -->

## Artifacts
Plans, research, and other durable session results go in `.ai/artifacts/`; tool-specific
folders are listed in `.ai/README.md`. Codex reads this file natively and uses the shared artifacts directory.

<!-- Initialized by init-ai-tooling __VERSION__ (__DATE__). -->
TPL
render <<'TPL' | write_file ".cursorrules"
# Cursor reads this file for compatibility. SOURCE OF TRUTH — ./AGENTS.md.
# Detailed rules — ./.cursor/rules/*.mdc. Read AGENTS.md before any work.
See AGENTS.md
TPL
render <<'TPL' | write_file ".cursor/rules/000-project.mdc"
---
description: Base project context for __NAME__ — points to AGENTS.md
alwaysApply: true
---

# __NAME__

Source of truth — `../../AGENTS.md` (read it fully). This file and sibling `*.mdc`
files hold Cursor-specific and detailed topical rules only.
TPL
render <<'TPL' | write_file ".cursor/rules/010-safety.mdc"
---
description: Security, secrets, production work
alwaysApply: true
---

# Security

- Secrets (passwords, keys, tokens, `.env`, local configs) — not in code, commits, or context.
- Do not edit production directly; destructive operations on production data — only
  with explicit confirmation and a dry run on a copy.
- Before a risky change — show a diff and rollback plan, ask for confirmation.
- Full rules — in `../../AGENTS.md`.
TPL
render <<'TPL' | write_file ".cursorignore"
# Secrets and local config
.env
*.local

# Build artifacts and data
dist/
build/
*.egg-info/

# Environments and caches
.venv/
venv/
node_modules/
__pycache__/
*.py[cod]
.pytest_cache/
.mypy_cache/
.ruff_cache/

.DS_Store
TPL
render <<'TPL' | write_file "CLAUDE.md"
# CLAUDE.md — __NAME__

Project rules live in `AGENTS.md`; the import below loads it into every Claude Code session.

@AGENTS.md

## Claude-specific
- `.claude/commands/` — slash commands; `.claude/agents/` — subagents; `.claude/artifacts/` — artifacts.
- Team settings — `.claude/settings.json`; personal — `.claude/settings.local.json` (do not commit).
- `settings.json` deny rules are guardrails, not a sandbox — see `.claude/README.md`.
TPL
render <<'TPL' | write_file ".claude/README.md"
# .claude/ — Claude Code configuration

Source of truth — [`../AGENTS.md`](../AGENTS.md).

- `commands/` — slash commands; `agents/` — subagents; `artifacts/` — Claude artifacts.
- `settings.json` — team settings; `settings.local.json` — personal (do not commit).

## What `settings.json` does NOT protect
The `deny` list is a best-effort guardrail, not a security boundary:
- `Bash(...)` rules match command prefixes: `rm -r -f`, `find . -delete`, or a script
  that deletes files are not caught.
- Without the sandbox, `Read(...)` rules cover Claude's file tools, not `cat .env` run through Bash.

For real isolation use Claude Code's sandbox, a container/devcontainer, or a `PreToolUse` hook.
TPL
render <<'TPL' | write_file ".claude/settings.json"
{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  "//": "Team Claude Code settings for __NAME_JSON__. Personal overrides — settings.local.json (do not commit). Deny rules are guardrails, not a sandbox: see .claude/README.md.",
  "permissions": {
    "allow": ["Read", "Edit"],
    "deny": [
      "Read(.env)",
      "Read(.env.*)",
      "Read(**.pem)",
      "Read(**.key)",
      "Read(**/.ssh/**)",
      "Read(**/.aws/**)",
      "Read(**/.kube/**)",
      "Bash(rm -rf:*)",
      "Bash(rm -fr:*)",
      "Bash(git push --force:*)",
      "Bash(git push -f:*)"
    ]
  }
}
TPL
render <<'TPL' | write_file "GEMINI.md"
# GEMINI.md — Google Antigravity / Gemini

> Antigravity reads both `AGENTS.md` and `GEMINI.md`; on conflict, `GEMINI.md` wins.
> **Project source of truth — `AGENTS.md`; read it first.** Here — Antigravity/Gemini specifics.

## Agent mode
- Work from a plan (task/plan): break the task down and show steps before executing.
- Human-in-the-loop: for production-data/core edits — stop and ask for confirmation.
- Produce artifacts (diff, file list, rollback plan) before applying; save them in `.antigravity/artifacts/`.
- Do not run shell commands against a production server/DB.
- Keep changes atomic, with an explanation of WHAT and WHY.
TPL
render <<'TPL' | write_file ".antigravity/README.md"
# .antigravity/ — Google Antigravity workspace

Rules — in [`../GEMINI.md`](../GEMINI.md); source of truth — [`../AGENTS.md`](../AGENTS.md).
`artifacts/` — plans, task lists, walkthroughs, browser recordings.
TPL
render <<'TPL' | write_file "PERPLEXITY.md"
# PERPLEXITY.md — brief for Perplexity / research agents

> Perplexity has no native repo config. This file is a **brief**: paste it into a
> prompt / Space (or Comet) to set role, context, and boundaries. Project context comes from `AGENTS.md`.

## Role
Research/content assistant for __NAME__.
<!-- TODO: clarify the role; whether it writes code; data access. -->

## What to use it for
<!-- TODO: research, fact-checking, drafts, competitive analysis. -->

## Boundaries
- Cite sources for facts; do not invent — mark unknowns as "needs verification".
- <!-- TODO: domain limits (ads/medicine/legal/etc.). -->

## Output format
Structured (Markdown/table), easy to transfer. Save as an artifact in `.perplexity/artifacts/`.
TPL
render <<'TPL' | write_file ".perplexity/README.md"
# .perplexity/ — Perplexity / research

Paste-in brief — [`../PERPLEXITY.md`](../PERPLEXITY.md); context — [`../AGENTS.md`](../AGENTS.md).
`artifacts/` — saved research reports (`YYYY-MM-DD-topic.md`; end with sources for verification).
TPL
render <<'TPL' | write_file ".ai/README.md"
# .ai/ — AI tooling layout

**Source of truth — [`../AGENTS.md`](../AGENTS.md)** (read natively by Codex, Cursor,
Antigravity/Gemini, and others). Everything else is a thin redirect or tool-specific detail.

| Tool | File | Artifacts |
|---|---|---|
| All agents | `AGENTS.md` | `.ai/artifacts/` |
| Codex (CLI / IDE / app) | `AGENTS.md` (native); optional `.codex/config.toml` | `.ai/artifacts/` |
| Cursor | `.cursorrules` → AGENTS.md; `.cursor/rules/*.mdc`; `.cursorignore` | `.cursor/artifacts/` |
| Claude (Code / Cowork) | `CLAUDE.md` → AGENTS.md; `.claude/` | `.claude/artifacts/` |
| Antigravity / Gemini | `GEMINI.md` (+ AGENTS.md) | `.antigravity/artifacts/` |
| Perplexity | `PERPLEXITY.md` (paste-in brief) | `.perplexity/artifacts/` |

## Rule
Project changes → edit **`AGENTS.md`**. Tool-specific detail → that tool's file.
Codex needs no redirect file; add `.codex/config.toml` only for concrete repository-specific
settings. An artifact is a durable session result (plan, research, diff, task list).

<!-- Initialized by init-ai-tooling __VERSION__ (__DATE__). -->
TPL
render <<'TPL' | write_file ".ai/manifest.json"
{
  "generator": "init-ai-tooling __VERSION__",
  "created": "__DATE__",
  "files": [
    "AGENTS.md",
    ".cursorrules",
    ".cursor/rules/000-project.mdc",
    ".cursor/rules/010-safety.mdc",
    ".cursorignore",
    "CLAUDE.md",
    ".claude/README.md",
    ".claude/settings.json",
    "GEMINI.md",
    ".antigravity/README.md",
    "PERPLEXITY.md",
    ".perplexity/README.md",
    ".ai/README.md",
    ".ai/manifest.json"
  ],
  "dirs": [
    ".ai/artifacts",
    ".claude/commands",
    ".claude/agents",
    ".claude/artifacts",
    ".cursor/artifacts",
    ".antigravity/artifacts",
    ".perplexity/artifacts"
  ]
}
TPL
}
# <<< END GENERATED

# ---------- artifact directories + .gitkeep ----------
for d in "${GITKEEP_DIRS[@]}"; do
  gitkeep "$d"
done

# ---------- templates ----------
emit_templates

# ---------- .gitignore ----------
if [ "$NO_GITIGNORE" != "1" ]; then
  ensure_add_ignore() {
    local line="$1"
    [ "$DRYRUN" = "1" ] && { say "gitignore += $line"; return 0; }
    touch .gitignore
    if ! grep -qxF "$line" .gitignore; then
      if [ -s .gitignore ] && [ -n "$(tail -c1 .gitignore 2>/dev/null)" ]; then
        printf '\n' >> .gitignore
      fi
      printf '%s\n' "$line" >> .gitignore
    fi
  }
  for line in "${GITIGNORE_LINES[@]}"; do
    ensure_add_ignore "$line"
  done
fi

say ""
say "Done (${VERSION}): AGENTS.md-model scaffold deployed for \"${NAME}\"."
say "Next: fill in the TODOs in AGENTS.md — every tool reads context from there."

if [ "$ALSO_REPO" = "1" ]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  COMPANION="${SCRIPT_DIR}/init-repo-bootstrap.sh"
  if [ ! -f "$COMPANION" ]; then
    echo "error: --also-repo requires init-repo-bootstrap.sh next to this script" >&2
    echo "       expected: ${COMPANION}" >&2
    exit 1
  fi
  say ""
  say "Also-repo: invoking init-repo-bootstrap.sh --profile ${REPO_PROFILE}"
  COMPANION_ARGS=(--name "$NAME" --desc "$DESC" --profile "$REPO_PROFILE")
  [ "$FORCE" = "1" ] && COMPANION_ARGS+=(--force)
  [ "$DRYRUN" = "1" ] && COMPANION_ARGS+=(--dry-run)
  bash "$COMPANION" "${COMPANION_ARGS[@]}"
else
  say "Tip: run init-repo-bootstrap.sh (or re-run with --also-repo) for LICENSE/SECURITY/CHANGELOG stubs."
fi

if [ "$DRYRUN" = "1" ] && [ "$ALSO_REPO" != "1" ]; then
  say "(dry-run: nothing was written)"
fi
exit 0
