<#
.SYNOPSIS
    init-ai-tooling.ps1 (2.0.0, AGENTS.md model) — PowerShell version for Windows 11/10.

.DESCRIPTION
    Deploys an AI tooling scaffold (Claude, Codex, Cursor, Gemini/Antigravity) in the
    current repository. Model: AGENTS.md = single source of truth; CLAUDE.md and
    GEMINI.md import it.

.PARAMETER Name
    Project name (defaults to the current folder name).

.PARAMETER Desc
    Short one-line description.

.PARAMETER Force
    Overwrite existing files.

.PARAMETER DryRun
    Print the plan, write nothing.

.PARAMETER NoGitignore
    Leave .gitignore alone.

.PARAMETER AlsoRepo
    Also run sibling init-repo-bootstrap.ps1 (B+).

.PARAMETER RepoProfile
    Profile for -AlsoRepo: core | github | full (default: full).

.PARAMETER PruneLegacy
    List leftovers from older kit versions and exit (deletes nothing).

.PARAMETER Version
    Print version and exit.

.EXAMPLE
    .\init-ai-tooling.ps1 -Name "my-project" -Desc "My project"
    powershell -ExecutionPolicy Bypass -File .\init-ai-tooling.ps1
#>
#Requires -Version 5.1
[CmdletBinding()]
param (
    [string]$Name = "",
    [string]$Desc = "",
    [switch]$Force,
    [switch]$DryRun,
    [switch]$NoGitignore,
    [switch]$AlsoRepo,
    [ValidateSet("core", "github", "full")]
    [string]$RepoProfile = "full",
    [switch]$PruneLegacy,
    [switch]$Version
)

# Separate constant from -Version: PowerShell variable names are case-insensitive.
$ToolVersion = "2.0.0"

$ErrorActionPreference = "Stop"

if ($Version) {
    Write-Host "init-ai-tooling.ps1 $ToolVersion"
    exit 0
}

# Windows PowerShell 5.1 defaults to OEM encoding (CP437/CP866) — without this
# non-ASCII text in messages becomes "?????". Swallow errors: in some hosts
# (ISE, redirected stdout) assignment is unavailable and that is not fatal.
try { [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding($false) } catch { }

# .NET resolves relative paths via [Environment]::CurrentDirectory, which is NOT
# synced with PowerShell's current location. Without this line [System.IO.*]
# would write to the process start directory, not where the user cd'd.
if ($PWD.Provider.Name -ne 'FileSystem') {
    throw ("Run the script from a filesystem directory. Current location: " +
           "$($PWD.Path) (provider $($PWD.Provider.Name)).")
}
[Environment]::CurrentDirectory = $PWD.ProviderPath

if ([string]::IsNullOrWhiteSpace($Name)) {
    $Name = (Get-Item -Path .).Name
}
if ([string]::IsNullOrWhiteSpace($Desc)) {
    $Desc = "TODO: short project description"
}
$Date = (Get-Date -Format "yyyy-MM-dd")
# Separate value for JSON substitution: quotes and backslashes in the project name
# would otherwise invalidate .claude/settings.json.
$NameJson = $Name.Replace('\', '\\').Replace('"', '\"')

function Say([string]$msg = "") {
    Write-Host $msg
}

function Write-Utf8LfFile {
    param (
        [string]$Path,
        [string]$Content
    )
    $parent = [System.IO.Path]::GetDirectoryName($Path)
    if ($parent -and -not (Test-Path $parent)) {
        [System.IO.Directory]::CreateDirectory($parent) | Out-Null
    }
    # Normalize to LF; non-empty files end with \n, matching Python/bash templates
    # (here-strings in PowerShell do not always keep the newline before closing '@).
    $lfContent = $Content -replace "`r`n", "`n" -replace "`r", "`n"
    if ($lfContent.Length -gt 0 -and -not $lfContent.EndsWith("`n")) {
        $lfContent += "`n"
    }
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $lfContent, $utf8NoBom)
}

function Initialize-Directory {
    param ([string]$Dir)
    if ($DryRun) {
        Say ("mkdir  " + ($Dir -replace "\\", "/"))
    } else {
        if (-not (Test-Path $Dir)) {
            [System.IO.Directory]::CreateDirectory($Dir) | Out-Null
        }
    }
}

function Write-Gitkeep {
    param ([string]$Dir)
    Initialize-Directory $Dir
    $filePath = Join-Path $Dir ".gitkeep"
    if ((Test-Path $filePath) -and -not $Force) {
        return
    }
    if ($DryRun) {
        Say ("touch  " + ($filePath -replace "\\", "/"))
        return
    }
    Write-Utf8LfFile -Path $filePath -Content ""
}

function Write-ProjectFile {
    param (
        [string]$RelPath,
        [string]$Content
    )
    if ((Test-Path $RelPath) -and -not $Force) {
        Say ("skip   " + ($RelPath -replace "\\", "/") + " (already exists)")
        return
    }
    if ($DryRun) {
        Say ("write  " + ($RelPath -replace "\\", "/"))
        return
    }
    # .Replace() — literal substitution. -replace would treat $Name/$Desc as regex
    # substitution ($1, $&, $$), breaking descriptions containing dollar signs.
    $rendered = $Content.Replace("__NAME_JSON__", $NameJson).Replace("__NAME__", $Name).Replace("__DESC__", $Desc).Replace("__DATE__", $Date).Replace("__VERSION__", $ToolVersion)
    Write-Utf8LfFile -Path $RelPath -Content $rendered
    Say ("write  " + ($RelPath -replace "\\", "/"))
}

# >>> BEGIN GENERATED by tools/sync-templates.py (edit templates/, not this block)
$GitkeepDirs = @(
    ".ai/artifacts",
    ".claude/commands",
    ".claude/agents"
)
$GitignoreLines = @(
    ".env",
    ".env.*",
    "!.env.example",
    "*.local",
    ".claude/settings.local.json",
    ".DS_Store"
)
$LegacyFiles = @(
    ".cursorrules",
    "PERPLEXITY.md",
    ".perplexity/README.md",
    ".antigravity/README.md",
    ".ai/shared-context.md",
    ".cursor/README.md",
    ".cursor/rules/.gitkeep",
    ".perplexity/context.md",
    ".perplexity/spaces/README.md",
    ".antigravity/rules/000-workspace.md",
    ".antigravity/rules/.gitkeep"
)
$LegacyArtifactDirs = @(
    ".claude/artifacts",
    ".cursor/artifacts",
    ".antigravity/artifacts",
    ".perplexity/artifacts"
)

# Templates in write order. Here-strings drop the final newline;
# Write-Utf8LfFile adds it back.
$ProjectFiles = @(
    [pscustomobject]@{ Path = "AGENTS.md"; Content = @'
# AGENTS.md — __NAME__

> Shared instructions for AI coding agents and humans. Codex, Cursor, Google Antigravity/Gemini,
> and other AGENTS-compatible tools read this file natively; Claude Code imports it from `CLAUDE.md`.
> Keep it short: write down only what an agent cannot infer from the code.

## Project
__DESC__

<!-- TODO: 1–3 sentences — what it is, who uses it, what matters most. -->

## Commands
<!-- TODO: exact commands an agent should run, e.g. install, test, lint, build. -->

## Conventions
<!-- TODO: only non-obvious rules — module boundaries, generated code not to edit, naming. -->

## Never
- Commit or print secrets (`.env`, keys, tokens); only `*.example` files belong in the repo.
- Run destructive operations on production data without explicit confirmation.
- <!-- TODO: project-specific bans (e.g. do not touch `vendor/`). -->

## Done means
Tests and lint pass for the change. <!-- TODO: add project-specific checks. -->

## Artifacts
Plans, research, and other durable session results from every tool go in `.ai/artifacts/`.
Codex reads this file natively and uses the shared artifacts directory.

<!-- Initialized by init-ai-tooling __VERSION__ (__DATE__). -->
'@ }
    [pscustomobject]@{ Path = ".cursor/rules/000-project.mdc"; Content = @'
---
description: Base project context for __NAME__ — points to AGENTS.md
alwaysApply: true
---

# __NAME__

Source of truth — `../../AGENTS.md` (read it fully). This file and sibling `*.mdc`
files hold Cursor-specific and detailed topical rules only.
'@ }
    [pscustomobject]@{ Path = ".cursor/rules/010-safety.mdc"; Content = @'
---
description: Security, secrets, production work
alwaysApply: true
---

# Security

- Secrets (passwords, keys, tokens, `.env`, local configs) — not in code, commits, or context.
- Do not edit production directly; destructive operations on production data — only
  with explicit confirmation and a dry run on a copy.
- Before a risky change — show a diff and rollback plan, ask for confirmation.
- Full rules — in `../../AGENTS.md`.
'@ }
    [pscustomobject]@{ Path = ".cursorignore"; Content = @'
# Secrets and local config
.env
*.local

# Build artifacts and data
dist/
build/
*.egg-info/

# Environments and caches
.venv/
venv/
node_modules/
__pycache__/
*.py[cod]
.pytest_cache/
.mypy_cache/
.ruff_cache/

.DS_Store
'@ }
    [pscustomobject]@{ Path = "CLAUDE.md"; Content = @'
# CLAUDE.md — __NAME__

Project rules live in `AGENTS.md`; the import below loads it into every Claude Code session.

@AGENTS.md

## Claude-specific
- `.claude/commands/` — slash commands; `.claude/agents/` — subagents.
- Team settings — `.claude/settings.json`; personal — `.claude/settings.local.json` (do not commit).
- `settings.json` deny rules are guardrails, not a sandbox — see `.claude/README.md`.
'@ }
    [pscustomobject]@{ Path = ".claude/README.md"; Content = @'
# .claude/ — Claude Code configuration

Source of truth — [`../AGENTS.md`](../AGENTS.md).

- `commands/` — slash commands; `agents/` — subagents. Artifacts go in `../.ai/artifacts/`.
- `settings.json` — team settings; `settings.local.json` — personal (do not commit).

## What `settings.json` does NOT protect
The `deny` list is a best-effort guardrail, not a security boundary:
- `Bash(...)` rules match command prefixes: `rm -r -f`, `find . -delete`, or a script
  that deletes files are not caught.
- Without the sandbox, `Read(...)` rules cover Claude's file tools, not `cat .env` run through Bash.

For real isolation use Claude Code's sandbox, a container/devcontainer, or a `PreToolUse` hook.
'@ }
    [pscustomobject]@{ Path = ".claude/settings.json"; Content = @'
{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  "//": "Team Claude Code settings for __NAME_JSON__. Personal overrides — settings.local.json (do not commit). Deny rules are guardrails, not a sandbox: see .claude/README.md.",
  "permissions": {
    "allow": ["Read", "Edit"],
    "deny": [
      "Read(.env)",
      "Read(.env.*)",
      "Read(**.pem)",
      "Read(**.key)",
      "Read(**/.ssh/**)",
      "Read(**/.aws/**)",
      "Read(**/.kube/**)",
      "Bash(rm -rf:*)",
      "Bash(rm -fr:*)",
      "Bash(git push --force:*)",
      "Bash(git push -f:*)"
    ]
  }
}
'@ }
    [pscustomobject]@{ Path = "GEMINI.md"; Content = @'
# GEMINI.md — __NAME__

Project rules live in `AGENTS.md`; the import below loads it into Gemini CLI.
Google Antigravity reads `AGENTS.md` natively.

@./AGENTS.md

## Gemini-specific
<!-- TODO: only what differs for Gemini CLI / Antigravity; leave empty if nothing does. -->
'@ }
    [pscustomobject]@{ Path = ".ai/README.md"; Content = @'
# .ai/ — AI tooling layout

**Source of truth — [`../AGENTS.md`](../AGENTS.md)** (read natively by Codex, Cursor,
Antigravity/Gemini, and others). Other files only add tool-specific detail.

| Tool | File | Artifacts |
|---|---|---|
| All agents | `AGENTS.md` | `.ai/artifacts/` |
| Codex (CLI / IDE / app) | `AGENTS.md` (native); optional `.codex/config.toml` | `.ai/artifacts/` |
| Cursor | `AGENTS.md` (native); `.cursor/rules/*.mdc`; `.cursorignore` | `.ai/artifacts/` |
| Claude (Code / Cowork) | `CLAUDE.md` (`@AGENTS.md` import); `.claude/` | `.ai/artifacts/` |
| Gemini CLI / Antigravity | `GEMINI.md` (`@AGENTS.md` import); Antigravity reads `AGENTS.md` | `.ai/artifacts/` |

## Rule
Project changes → edit **`AGENTS.md`**. Tool-specific detail → that tool's file.
Codex needs no redirect file; add `.codex/config.toml` only for concrete repository-specific
settings. An artifact is a durable session result (plan, research, diff, task list).
`manifest.json` lists the files this kit generated; `--prune-legacy` reports leftovers
from older kit versions.

<!-- Initialized by init-ai-tooling __VERSION__ (__DATE__). -->
'@ }
    [pscustomobject]@{ Path = ".ai/manifest.json"; Content = @'
{
  "generator": "init-ai-tooling __VERSION__",
  "created": "__DATE__",
  "files": [
    "AGENTS.md",
    ".cursor/rules/000-project.mdc",
    ".cursor/rules/010-safety.mdc",
    ".cursorignore",
    "CLAUDE.md",
    ".claude/README.md",
    ".claude/settings.json",
    "GEMINI.md",
    ".ai/README.md",
    ".ai/manifest.json"
  ],
  "dirs": [
    ".ai/artifacts",
    ".claude/commands",
    ".claude/agents"
  ]
}
'@ }
)
# <<< END GENERATED

# -PruneLegacy: report only, never deletes.
if ($PruneLegacy) {
    $found = 0
    Say "Legacy paths from earlier kit versions (nothing is deleted):"
    foreach ($rel in $LegacyFiles) {
        if (Test-Path -LiteralPath $rel -PathType Leaf) {
            Say "  $rel"
            $found++
        }
    }
    foreach ($rel in $LegacyArtifactDirs) {
        if (-not (Test-Path -LiteralPath $rel -PathType Container)) { continue }
        $found++
        try {
            $saved = @(Get-ChildItem -LiteralPath $rel -Force -ErrorAction Stop | Where-Object { $_.Name -ne ".gitkeep" }).Count
        } catch {
            Say "  $rel/ (unreadable: check it manually)"
            continue
        }
        if ($saved -gt 0) {
            Say "  $rel/ ($saved saved item(s): move them to .ai/artifacts/ first)"
        } else {
            Say "  $rel/"
        }
    }
    if ($found -gt 0) {
        Say "Review each path, then remove it, e.g.: git rm -r <path>"
    } else {
        Say "  none found"
    }
    exit 0
}

# 1) artifact directories + .gitkeep
foreach ($d in $GitkeepDirs) {
    Write-Gitkeep $d
}

# 2) template files
foreach ($f in $ProjectFiles) {
    Write-ProjectFile $f.Path $f.Content
}

# 3) .gitignore
if (-not $NoGitignore) {
    $gitignorePath = ".gitignore"
    $existingLines = @()
    if (Test-Path $gitignorePath) {
        # @(...) required: Get-Content on a single-line file returns a scalar String,
        # and later += would concatenate strings instead of appending to an array.
        $existingLines = @(Get-Content -Path $gitignorePath -Encoding UTF8)
    }
    $linesToAdd = $GitignoreLines
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)

    foreach ($line in $linesToAdd) {
        if (-not ($existingLines -ccontains $line)) {
            if ($DryRun) {
                Say "gitignore += $line"
            } else {
                if ([System.IO.File]::Exists($gitignorePath) -and (New-Object System.IO.FileInfo($gitignorePath)).Length -gt 0) {
                    $rawBytes = [System.IO.File]::ReadAllBytes($gitignorePath)
                    if ($rawBytes[-1] -ne 10) {
                        [System.IO.File]::AppendAllText($gitignorePath, "`n", $utf8NoBom)
                    }
                }
                [System.IO.File]::AppendAllText($gitignorePath, "$line`n", $utf8NoBom)
                $existingLines += $line
            }
        }
    }
}

Say ""
Say "Done (${ToolVersion}): AGENTS.md-model scaffold deployed for `"$Name`"."
Say "Next: fill in the TODOs in AGENTS.md — every tool reads context from there."

if ($AlsoRepo) {
    $companion = Join-Path $PSScriptRoot "init-repo-bootstrap.ps1"
    if (-not (Test-Path $companion)) {
        throw "AlsoRepo requires init-repo-bootstrap.ps1 next to this script: $companion"
    }
    Say ""
    Say "Also-repo: invoking init-repo-bootstrap.ps1 -Profile $RepoProfile"
    $companionArgs = @{
        Name = $Name
        Desc = $Desc
        Profile = $RepoProfile
    }
    if ($Force) { $companionArgs.Force = $true }
    if ($DryRun) { $companionArgs.DryRun = $true }
    & $companion @companionArgs
    if (-not $?) {
        exit 1
    }
} else {
    Say "Tip: run init-repo-bootstrap.ps1 (or re-run with -AlsoRepo) for LICENSE/SECURITY/CHANGELOG stubs."
}

if ($DryRun -and -not $AlsoRepo) {
    Say "(dry-run: nothing was written)"
}
