#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate the template blocks embedded in the six init scripts.

templates/<family>/*.tpl + layout.json and the root VERSION file are the single
source of truth. Each script keeps its hand-written logic and carries one
generated block between the BEGIN/END markers, so the scripts stay
self-contained (one file to copy) while every template edit happens once.

Usage:
    python3 tools/sync-templates.py          # rewrite generated blocks in place
    python3 tools/sync-templates.py --check  # exit 1 if any script is stale (CI)
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOM = b"\xef\xbb\xbf"
BEGIN = "# >>> BEGIN GENERATED by tools/sync-templates.py (edit templates/, not this block)"
END = "# <<< END GENERATED"
PROFILE_RANK = {"core": 0, "github": 1, "full": 2}
MANIFEST_PATH = ".ai/manifest.json"
# layout.json values are pasted into bash words, Python and PowerShell double-quoted
# strings unescaped; this charset is inert in all three.
SAFE_LAYOUT_VALUE = re.compile(r"[A-Za-z0-9._/*!-]+")
# Plain string lists in layout.json and their names in each language.
LIST_KEYS = ("gitkeep_dirs", "gitignore", "legacy_files", "legacy_artifact_dirs")
VAR_NAMES = {"gitkeep_dirs": "GITKEEP_DIRS", "gitignore": "GITIGNORE_LINES",
            "legacy_files": "LEGACY_FILES", "legacy_artifact_dirs": "LEGACY_ARTIFACT_DIRS"}
PS_NAMES = {"gitkeep_dirs": "$GitkeepDirs", "gitignore": "$GitignoreLines",
            "legacy_files": "$LegacyFiles", "legacy_artifact_dirs": "$LegacyArtifactDirs"}

SCRIPTS = {
    "ai": ("init-ai-tooling.sh", "init_ai_tooling.py", "init-ai-tooling.ps1"),
    "repo": ("init-repo-bootstrap.sh", "init_repo_bootstrap.py", "init-repo-bootstrap.ps1"),
}

# Lines that carry the release number, per script type.
VERSION_PATTERNS = {
    ".sh": [r'^(VERSION=")[^"]+(")$', r"^(# init-[a-z-]+\.sh \()[0-9.]+"],
    ".py": [r'^(VERSION = ")[^"]+(")$', r'^("""init_[a-z_]+\.py \()[0-9.]+'],
    ".ps1": [r'^(\$ToolVersion = ")[^"]+(")$', r"^(    init-[a-z-]+\.ps1 \()[0-9.]+"],
}


class TemplateError(Exception):
    pass


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------
def load_family(family):
    base = ROOT / "templates" / family
    layout = json.loads((base / "layout.json").read_text(encoding="utf-8"))
    validate_layout(family, layout)
    entries = []
    for item in layout["files"]:
        path, profile = (item, None) if isinstance(item, str) else (item["path"], item["profile"])
        if profile is not None and profile not in PROFILE_RANK:
            raise TemplateError("%s: unknown profile %r" % (path, profile))
        content = (base / (path + ".tpl")).read_text(encoding="utf-8")
        validate_template(family, path, content)
        entries.append((profile, path, content))
    if family == "ai":
        entries.append((None, MANIFEST_PATH, manifest_template(layout)))
    return layout, entries


def manifest_template(layout):
    """Kit-owned paths, so future upgrades can tell generated files from user files."""
    manifest = {
        "generator": "init-ai-tooling __VERSION__",
        "created": "__DATE__",
        "files": list(layout["files"]) + [MANIFEST_PATH],
        "dirs": list(layout.get("gitkeep_dirs", [])),
    }
    return json.dumps(manifest, indent=2) + "\n"


def validate_layout(family, layout):
    values = [v for key in LIST_KEYS for v in layout.get(key, [])]
    for item in layout["files"]:
        values += [item] if isinstance(item, str) else [item["path"], item["profile"]]
    for value in values:
        if not SAFE_LAYOUT_VALUE.fullmatch(value):
            raise TemplateError("templates/%s/layout.json: unsafe value %r (allowed: %s)"
                                % (family, value, SAFE_LAYOUT_VALUE.pattern))


def validate_template(family, path, content):
    """Reject content that one of the three embeddings cannot represent verbatim."""
    where = "templates/%s/%s.tpl" % (family, path)
    if "\r" in content:
        raise TemplateError(where + ": CR characters (templates must be LF)")
    if not content.endswith("\n") or content.endswith("\n\n"):
        raise TemplateError(where + ": must end with exactly one newline")
    lines = content.split("\n")
    if "TPL" in lines:
        raise TemplateError(where + ": a line equal to TPL would end the bash heredoc")
    if any(line.startswith("'@") for line in lines):
        raise TemplateError(where + ": a line starting with '@ would end the PowerShell here-string")
    if '"""' in content:
        raise TemplateError(where + ': contains """ (would end the Python literal)')


# ---------------------------------------------------------------------------
# Rendering one generated block per language
# ---------------------------------------------------------------------------
def py_literal(content):
    return '"""\\\n' + content.replace("\\", "\\\\") + '"""'


def render_python(family, layout, entries):
    out = []
    if family == "ai":
        for key in LIST_KEYS:
            out.append("%s = [" % VAR_NAMES[key])
            out += ['    "%s",' % value for value in layout[key]]
            out.append("]")
            out.append("")
        out.append("# (path, template) in write order.")
        out.append("FILES = [")
        for _, path, content in entries:
            out.append('    ("%s", %s),' % (path, py_literal(content)))
    else:
        out.append("# (profile, path, template) in write order.")
        out.append("FILES = [")
        for profile, path, content in entries:
            out.append('    ("%s", "%s", %s),' % (profile, path, py_literal(content)))
    out.append("]")
    return out


def bash_word(value):
    return "'%s'" % value


def render_bash(family, layout, entries):
    out = []
    if family == "ai":
        for key in LIST_KEYS:
            out.append("%s=(%s)" % (VAR_NAMES[key], " ".join(bash_word(v) for v in layout[key])))
        out.append("")
    out.append("# Writes every template in order (render | write_file).")
    out.append("emit_templates() {")
    for profile, path, content in entries:
        guarded = profile not in (None, "core")
        if guarded:
            out.append("if profile_includes %s; then" % profile)
        out.append("render <<'TPL' | write_file \"%s\"" % path)
        out += content.rstrip("\n").split("\n")
        out.append("TPL")
        if guarded:
            out.append("fi")
    out.append("}")
    return out


def render_powershell(family, layout, entries):
    out = []
    if family == "ai":
        for key in LIST_KEYS:
            out.append("%s = @(" % PS_NAMES[key])
            out.append(",\n".join('    "%s"' % v for v in layout[key]))
            out.append(")")
        out.append("")
    out.append("# Templates in write order. Here-strings drop the final newline;")
    out.append("# Write-Utf8LfFile adds it back.")
    out.append("$ProjectFiles = @(")
    for profile, path, content in entries:
        head = '    [pscustomobject]@{ Path = "%s"; ' % path
        if family == "repo":
            head += 'Profile = "%s"; ' % profile
        out.append(head + "Content = @'")
        out += content.rstrip("\n").split("\n")
        out.append("'@ }")
    out.append(")")
    return out


RENDERERS = {".py": render_python, ".sh": render_bash, ".ps1": render_powershell}


# ---------------------------------------------------------------------------
# Splicing
# ---------------------------------------------------------------------------
def read_script(path):
    raw = path.read_bytes()
    has_bom = raw.startswith(BOM)
    text = raw[len(BOM):].decode("utf-8") if has_bom else raw.decode("utf-8")
    crlf = "\r\n" in text
    return text.replace("\r\n", "\n"), has_bom, crlf


def encode_script(text, has_bom, crlf):
    if crlf:
        text = text.replace("\n", "\r\n")
    data = text.encode("utf-8")
    return BOM + data if has_bom else data


def splice(text, block_lines, script_name):
    lines = text.split("\n")
    try:
        start = lines.index(BEGIN)
        end = lines.index(END, start)
    except ValueError:
        raise TemplateError("%s: generated-block markers not found" % script_name)
    return "\n".join(lines[: start + 1] + block_lines + lines[end:])


def apply_version(text, suffix, version, script_name):
    for pattern in VERSION_PATTERNS[suffix]:
        regex = re.compile(pattern, re.M)
        if not regex.search(text):
            raise TemplateError("%s: version line not found (%s)" % (script_name, pattern))
        text = regex.sub(lambda m: m.group(1) + version + (m.group(2) if m.lastindex > 1 else ""), text)
    return text


def build(version):
    """{path: expected bytes} for every script."""
    expected = {}
    for family, names in SCRIPTS.items():
        layout, entries = load_family(family)
        for name in names:
            path = ROOT / name
            suffix = path.suffix
            text, has_bom, crlf = read_script(path)
            block = RENDERERS[suffix](family, layout, entries)
            text = splice(text, block, name)
            text = apply_version(text, suffix, version, name)
            expected[path] = encode_script(text, has_bom, crlf)
    return expected


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="Fail if scripts are stale; write nothing.")
    args = parser.parse_args(argv)

    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        print("VERSION must be MAJOR.MINOR.PATCH, got %r" % version)
        return 1
    try:
        expected = build(version)
    except (TemplateError, OSError, ValueError, KeyError) as exc:
        print("error: %s" % exc)
        return 1

    stale = [p for p, data in expected.items() if p.read_bytes() != data]
    if args.check:
        for path in stale:
            print("stale: %s (run: python3 tools/sync-templates.py)" % path.name)
        if not stale:
            print("Generated blocks are up to date (%d scripts, version %s)." % (len(expected), version))
        return 1 if stale else 0

    for path in stale:
        path.write_bytes(expected[path])
        print("updated %s" % path.name)
    if not stale:
        print("Nothing to update.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
